apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  selector: # Used for managing pods with the same lable
    matchLabels:
      app: hello-k8s
  replicas: 4
  template: # Pod template
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: kenechukwujosiah/hello-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
