apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-2-nginx
spec:
  selector:
    app: hello-k8s-2-nginx
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-2-nginx
spec:
  selector: # Used for managing pods with the same lable
    matchLabels:
      app: hello-k8s-2-nginx
  replicas: 4
  template: # Pod template
    metadata:
      labels:
        app: hello-k8s-2-nginx
    spec:
      containers:
        - name: hello-k8s-2-nginx
          image: kenechukwujosiah/hello-k8s-2-nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
